### ISSUE TITLE
AWS-vault

### ISSUE THREAD

**Issue by Mehdi-Bl** [claranet/sshm#1]
How to support aws-vault & so have the credentials encrypted instead of store in clear text in AWS profile?

**Comment by Issif** [comment]
Hi @MBlagui ,

I use the official Golang SDK, it means you can use any authentication method provided by AWS exactly like it's possible with **aws-cli**. I never used **aws-vault** but if it works with other tools like **aws-cli** or **awless** it should work too.

**Comment by jamengual** [comment]
I use aws-vault every day, sshm works with or without aws-vault but you need always at least 1 pair of key/secrets for aws-vault to work.

if you run `aws-vault exec profilename -- aws s3 ls` it will create a session it will cache it and then even if you run aws cli without aws-vault it will still work. All this depends how the IAM policies for STS are set up in your account but this has nothing to do with this tool in particular.

**Comment by Issif** [comment]
Thanks @jamengual for the answer, it will help others for sure.
