### ISSUE TITLE
read region from AWS_REGION and if not present set a default 

### ISSUE THREAD

**Issue by jamengual** [claranet/sshm#3]
Hi.

I love the took and I have been using it for some time but every so often I forget to set the region and then I get not instances found error, it will be cool if instead of defaulting to eu-west it actually read the environment variable AWS_REGION first or the profile configured region.

Thanks.

**Comment by Issif** [comment]
Have you tried with `AWS_DEFAULT_REGION` envvar ?

See : https://github.com/claranet/sshm/blob/master/main.go#L64

**Comment by jamengual** [comment]
I use aws-vault and my env looks like : 
```
AWS_DEFAULT_REGION=us-east-2
AWS_REGION=us-east-2
```
and I have to specify the region otherwise it does not find the instances

**Comment by Issif** [comment]
OK, I will take a look but I don't use the tool anymore (I'm not working anymore at Claranet)

**Comment by Issif** [comment]
@jamengual It should fix your issue : https://github.com/claranet/sshm/releases/tag/1.2.1

**Comment by jamengual** [comment]
now it works from `aws-vault` but without it it does not and now I wonder should this be reading from my ~/.aws/config profiles ?

since in my profiles I specify a region this should read those ?

**Comment by Issif** [comment]
It never used the `region` parameter in `.aws/config` I guess I should add it. Is that urgent for you or is it okay with `aws-vault` for now?

**Comment by jamengual** [comment]
is not urgent but I think it is expected standard.
a coworker run into that problem.

**Comment by Issif** [comment]
@jamengual [1.2.2](https://github.com/claranet/sshm/releases/tag/1.2.2) it should be OK 😉

**Comment by jamengual** [comment]
works perfectly, thanks again.
